twitter/pelikan

CMakeLists.txt
deps/ccommon/CMakeLists.txt

This reduces the dependency requirement when building docker images (otherwise we will have to pull g++ when building image based on debian:jessie)

declare project as C-only to avoid looking for CXX related symbols

---

deps/ccommon/CMakeLists.txt
deps/ccommon/config.h.in
deps/ccommon/docs/c-styleguide.txt
deps/ccommon/include/cc_array.h
deps/ccommon/include/cc_define.h
deps/ccommon/include/cc_mm.h
deps/ccommon/include/cc_signal.h
deps/ccommon/src/cc_debug.c
deps/ccommon/src/cc_mm.c
deps/ccommon/src/cc_signal.c
src/core/data/worker.c
src/core/data/worker.h
src/protocol/data/memcache/compose.c

This addresses https://github.com/twitter/pelikan/issues/116
We are wiating only for either read or write event at any given point, so difficulty to write to socket will translate (eventually) to back pressure by ignoring incoming data from the same channel.

disable EVENT_READ when waiting for EVENT_WRITE, and vice versa

---

.gitignore
.travis.yml
test/integration/base.py
test/integration/pelikan_client.py
test/integration/pelikan_server.py
test/integration/test_twemcache_basic.py

kick off for issue #129 ; not complete, I want to gather feedback before moving on

Add basic python integration test

---

.travis.yml
src/server/pingserver/admin/process.c
src/server/slimcache/admin/process.c
src/server/twemcache/admin/process.c
test/integration/pelikan_client.py

- fix: remove extra '\0' at the end of stats response due to incorrect length calculation
- The local tests are successful but on travis CI it's failing. disable test until we know why

fix bug shown in integration test

---

.travis.yml
config/twemcache_test.conf
src/core/data/worker.c
src/core/data/worker.h
src/protocol/admin/request.h
src/protocol/data/memcache/klog.c
src/protocol/data/memcache/parse.c
src/protocol/data/memcache/request.c
src/protocol/data/memcache/request.h
src/protocol/data/memcache/response.c
src/server/twemcache/data/process.c
src/server/twemcache/data/process.h
src/server/twemcache/main.c
src/storage/slab/item.c
src/storage/slab/item.h
src/storage/slab/slab.c
src/storage/slab/slab.h
test/protocol/data/memcache/check_memcache.c
test/storage/slab/check_slab.c

This is the first diff to address issue #122 
Subsequent diff will add more unit tests, as well as handle partial value when writing responses (when wbuf is full)

make twemcache deal with partial request value

---

src/protocol/admin/parse.c
src/server/twemcache/admin/process.c
src/storage/slab/item.c
src/storage/slab/slab.c
src/storage/slab/slab.h

We deviate from memcached's slab metrics format because honestly it was not particular readable. Now they look like this:
```
stats slab
CLASS 1: chunk_size 48 item_keyval_byte 0 item_val_byte 0 item_curr 0 item_free 0 slab_curr 0
CLASS 2: chunk_size 56 item_keyval_byte 0 item_val_byte 0 item_curr 0 item_free 0 slab_curr 0
CLASS 3: chunk_size 64 item_keyval_byte 0 item_val_byte 0 item_curr 0 item_free 0 slab_curr 0
...
END
```
Compatibility is not important because internally we never exported these numbers anywhere, and the current table format is easier to read than one metric per line.

Add perslab metrics that help understand item size distribution

---

src/core/data/worker.c
src/core/data/worker.h
src/server/pingserver/data/process.c
src/server/pingserver/data/process.h
src/server/pingserver/main.c
src/server/slimcache/data/process.c
src/server/slimcache/data/process.h
src/server/slimcache/main.c
src/server/twemcache/data/process.c
src/server/twemcache/data/process.h
src/server/twemcache/main.c

While working on a pubsub prototype, it was evident that the processing logic has to be aware of the identification of the channel to properly index all subscribers. This prompts me to change the signature of the worker thread to accommodate this use case.
Note buf_sock is not quite the final signature I want- I would like to pass in the stream object, which is the abstract type for which buf_sock is an implementation. But this is not currently necessary as we only support buf_sock.
I would like to refactor both channel and stream in ccommon to make it easier to call the right methods (handlers) against various channel types (TCP socket, Unix domain socket, pipe, etc). And I would like to come back and further refactor the core functionalities when that is done in ccommon.

Change processor signature to expose buf_sock

---

src/core/data/server.c

Previous behavior generates way too many logs upon buf_sock exhaustion, leading to disk OOM since logrotate cannot keep up (at least not with copy truncate).
While eventually it would be nice to dedup logs and (maybe) implement cross-thread communication to re-enable connection acceptance upon closure of existing connections, for now it should be sufficient to slow down a bit on the server thread whenever we are out of memory.
As discussed in the comment, this probably encourages the client to back off, or allow kernel to shed some excessive connecting attempts via filling backlog queue(s).

sleep upon conn objection OOM

---

src/protocol/data/memcache/request.c
src/protocol/data/memcache/request.h
src/server/twemcache/data/process.c
test/integration/twemcache/seq-1

add a field in request struct to chain to response(s), so we can avoid allocating memory dynamically to keep track of req/rsp pointers

allow request to include to a response object

---

src/server/slimcache/data/process.c
src/storage/cuckoo/cuckoo.c
src/storage/cuckoo/cuckoo.h
test/storage/cuckoo/check_cuckoo.c

this will allow us to get the item after insert, this is useful if we want to follow up editing the values, which is useful for handling data structures.

change return type of cuckoo_insert

---

src/data_structure/ziplist/ziplist.c
src/data_structure/ziplist/ziplist.h
test/data_structure/ziplist/check_ziplist.c

the remove val API makes it easier to implement list command such as LREM.
allow find to accept `NULL` for both `ze` and `idx` so we can call this function just to check if a value exists or not, which is useful in testing and some higher level APIs.

add remove_val API implementation, allow found to only return state

---

src/protocol/data/memcache/constant.h
src/server/twemcache/data/process.c
src/storage/slab/item.c
src/storage/slab/item.h
src/storage/slab/slab.h
test/storage/slab/check_slab.c

Previously, slab follows memcached semantics a little too closely, especially the use of `dataflag`. This is a known issue / TODO. This PR addresses that.
After this change, metadata storage is generalized, and caller can specify how much metadata storage is needed when reserving an item, so that value is customizable not only per-backend type but also per-key.

refactor slab module to generalize dataflag into metadata storage

---

deps/ccommon/include/channel/cc_tcp.h
deps/ccommon/src/channel/cc_tcp.c
deps/ccommon/test/channel/tcp/check_tcp.c
src/core/admin/admin.c
src/core/data/server.c
src/core/data/shared.h
src/core/data/worker.c
src/server/twemcache/admin/process.c

This PR creates bidirectional pipes between server and worker, so worker can delegate all connection terminations to the server thread and avoid thread safety issues around stream/channel related resources.

Fixing issue #179

---

deps/ccommon/rust/cc_binding/build.rs
deps/ccommon/rust/ccommon_rs/src/bstring.rs
src/storage/cdb/cdb_ffi/src/lib.rs
src/storage/cdb/cdb_rs/src/cdb/input.rs
src/storage/cdb/cdb_rs/src/cdb/mod.rs

Ran the "clippy" tool against ccommon and pelikan and fixed all of the outstanding lint warnings/errors.

clean up a bunch of lint errors

---

src/server/redis/data/cmd_list.c
src/server/slimredis/data/cmd_bitmap.c
src/storage/cuckoo/cuckoo.c
src/time/time.h
test/storage/cuckoo/check_cuckoo.c
test/storage/slab/check_slab.c

Addresses #189. I believe using UINT32_MAX - 1 was in reaction to cuckoo, where we assumed that timestamp will be less than UINT32_MAX for the sake of expiry based eviction. This change updates the behavior to use INT32_MAX to mean unbounded expiry in all places, and slightly changes the behavior of cuckoo's selection for eviction when using CUCKOO_POLICY_EXPIRE policy when multiple items share the min expiry timestamp. The new behavior makes it so that instead of selecting the first one in this case, the last one will be selected since we now select if expiry is <= to the min we've inspected, rather than <. I don't think this should cause any issue.

Use INT32_MAX for unbounded expiry

---

src/server/redis/data/cmd_list.c
src/server/twemcache/data/process.c
src/storage/cuckoo/cuckoo.c
src/storage/cuckoo/cuckoo.h
src/storage/cuckoo/item.h
src/storage/slab/item.c
src/storage/slab/item.h
src/storage/slab/slab.c
src/storage/slab/slab.h
test/storage/cuckoo/check_cuckoo.c
test/storage/slab/check_slab.c

Add maximum TTL setting and unit tests, some item refactoring

---

src/server/twemcache/data/process.c
src/server/twemcache/data/process.h

This allows us to quickly fill a slab's heap with printed numeric keys/values, this is useful for performance tests.
Cache's RSS, which is primarily driven by the amount data stored in slab, is an important factor for performance. As memory gets bigger on modern hardware, it takes longer to fill the heap by external traffic. For example, if we want to warm up a 32GB heap, using 64 bit key+val sizes, we will need to create 300M keys. If we use 100K qps to warm it up, it will take almost an hour. This clearly makes realistic load testing fairly slow and expensive to conduct. In comparison, prefilling the memory inside the server can make this process at least an order of magnitude faster.
The implementation introduces a master switch `prefill`, and 3 options that control how prefilling …

add prefill option and logic to populate the slabs with data

---

deps/ccommon/test/ring_array/check_ring_array.c

Summary:
WARNING: ThreadSanitizer: thread leak (pid=73068)
Thread T1 (tid=6684080, finished) created by main thread at:
#0 pthread_create <null> (libclang_rt.tsan_osx_dynamic.dylib:x86_64h+0x2999d)
#1 test_thread check_ring_array.c:199 (check_ring_array:x86_64+0x10000231f)
#2 srunner_run_tagged <null> (libcheck.0.dylib:x86_64+0x4898)
#3 start <null> (libdyld.dylib:x86_64+0x1014)
ThreadSanitizer: thread leak check_ring_array.c:199 in test_thread

ThreadSanitizer: Fix thread leak in test_thread in ring_array suite

---

test/data_structure/bitmap/check_bitmap.c

Summary:
==79284==ERROR: AddressSanitizer: global-buffer-overflow on address
0x00010d405de8 at pc 0x00010d404f79 bp 0x7ffee27fc5c0 sp 0x7ffee27fc5b8
READ of size 2 at 0x00010d405de8 thread T0
#0 0x10d404f78 in test_bitset_getset check_bitmap.c:47
#1 0x10d40e898 in srunner_run_tagged (libcheck.0.dylib:x86_64+0x4898)
#2 0x10d404c04 in main check_bitmap.c:90
#3 0x7fff69fa2014 in start (libdyld.dylib:x86_64+0x1014)

Addresssanitizer: Fix buffer overflow in test_bitset_getset

---

src/core/data/server.c
src/protocol/data/memcache/response.c
src/server/twemcache/data/process.c

This leads to request object being double returned when the buf_sock object gets handed out again.

fix the bug of not resetting buf_sock object when terminating connections

---

CMakeLists.txt
deps/ccommon/CMakeLists.txt

Building on Ubuntu 18.04 fails with missing symbols message
due to lack of proper libraries being automatically linked
against tests.
This patch uses pkgconfig to automatically detect system-installed
libcheck, and also gets rid of the unnecessery symbol requirement in
favor of a simple version check.

cmake: fix check detection

---

CMakeLists.txt
benchmarks/CMakeLists.txt
benchmarks/bench_micro.c

This makes it far easier to benchmark just the storage layer.
It's very simplistic right now, but we can add things as needed (i.e., slab support).
... and I probably need to add better error handling ;)

benchmark: implement cuckoo micro benchmark

---

CMakeLists.txt
test-coverage.sh

- debug build type to pass O0 flag, other to pass O2 flag
- remove unnecessary flags from COVERAGE -g -Wall -W
- ref: twitter/ccommon@1c8df4200ca245fc87b07a235b490e91e88f7b48

Add basic support of build type

---

cmake/FindLIBPMEM.cmake
src/storage/slab/slab.h

Fix libpmem detection in case of pkg_config is missing 
Remove SLAB_HASH macro (all occurrences were replaced by HASH_POWER macro in b12de66)

Fix pkg config detection and code cleanup

---

src/server/slimcache/data/process.c

Using partial request, like from rpc-perf, causes first request
buffer not to be returned to requests pool.
This commits adds function which will return this buffer to pool.

Fix cleaning after partial request

---

scripts/load_testing/README.md
scripts/load_testing/client_config.py
scripts/load_testing/generate.sh
scripts/load_testing/server_config.py

Update server configs generating scripts (introduced in commit 809fb94):
- add slimcache support
- add PMEM parameters support
- provide Readme 
Additionally: Fix python3 octal literals handling

Update server configs generating scripts

---

CMakeLists.txt
src/data_structure/CMakeLists.txt
src/data_structure/intarray/CMakeLists.txt
src/data_structure/intarray/intarray.c
src/data_structure/intarray/intarray.h
src/storage/cuckoo/CMakeLists.txt
test/CMakeLists.txt
test/data_structure/CMakeLists.txt
test/data_structure/bitmap/CMakeLists.txt
test/data_structure/intarray/CMakeLists.txt
test/data_structure/intarray/check_intarray.c
test/data_structure/ziplist/CMakeLists.txt
test/data_structure/ziplist/check_ziplist.c
test/datapool/CMakeLists.txt
test/hotkey/kc_map/CMakeLists.txt
test/hotkey/key_window/CMakeLists.txt
test/protocol/admin/CMakeLists.txt
test/protocol/data/memcache/CMakeLists.txt
test/protocol/data/redis/CMakeLists.txt
test/storage/cuckoo/CMakeLists.txt
test/storage/slab/CMakeLists.txt
test/time/CMakeLists.txt

The intarray is designed for sorted array of integers of uniform but
configurable sizes, including 1-, 2-, 4-, 8-byte unsigned integers.
Because of the limitation on data type, intarray is both more memory-
efficient and faster for value lookups compared to a more generic data
structure such as ziplist. It is particularly useful if users intend to
keep a sorted list of numbers without duplication, such as an index of
numeric IDs.

initial check-in of intarray

---

src/protocol/data/resp/cmd_sarray.h
src/server/rds/data/cmd_sarray.c
src/server/rds/data/cmd_sarray.h
src/server/rds/data/shared.h

sarray_insert/remove now takes multiple arguments, and return the number of values successfully inserted/removed

allow multiple values in both sarray_insert/remove

---

scripts/load_testing/client_config.py
scripts/load_testing/server_config.py

- Rename rpc-perf parameter to tcp_nodelay
-  Fix value of slab_size to be equal exactly 1MiB

Fix pelikan scripts

---

test/integration/test_twemcache.py

- to avoid false positive results in make test return non zero value in case of failure of integration test

Fix integration test in make test call

---

ci/run.sh
deps/ccommon/cmake/CMakeCargo.cmake
deps/ccommon/cmake/CargoLink.cmake
deps/ccommon/cmake/CargoTest.cmake
src/rust-util/pelikan-sys/Cargo.toml
src/rust-util/pelikan-sys/build.rs
src/rust-util/pelikan/src/core/admin.rs

This reduces unnecessary rebuilds by not specifying RUSTFLAGS when not needed.
It also adds an override flag `CARGO_FORCE_CMAKE_LINK` to force all crates to use cmake-supplied linker flags in case that's necessary in some configurations. Note that if a crate actually needs this it should pass `USE_CMAKE_LINK` to `cargo_build` within the configuration file.
The CI build is still slow (and it appears that some crates are still rebuilt redundantly) but this seems to shorten it by about 10 mins.
This PR contains changes to ccommon, those will be backported in a separate PR.

Speed up rust builds

---

src/rust-util/pelikan-sys/build.rs

This ensures that libraries that have multiple levels of C dependencies (see #276) link properly on linux.

Fix the order that link declarations are printed in pelikan-sys build script

---

Cargo.lock
Cargo.toml
src/rust-util/CMakeLists.txt
src/rust-util/httpencode/CMakeLists.txt
src/rust-util/httpencode/Cargo.toml
src/rust-util/httpencode/benches/compose.rs
src/rust-util/httpencode/src/error.rs
src/rust-util/httpencode/src/http.rs
src/rust-util/httpencode/src/lib.rs
src/rust-util/httpencode/src/request.rs
src/rust-util/httpencode/src/response.rs
src/rust-util/httpencode/src/tests.rs
src/rust-util/httpencode/src/traits.rs
src/rust-util/httpencode/src/util.rs

This moves the httpencode library (which is used by the twemcache-http PR) into pelikan.

Add httpencode library to pelikan

---

src/data_structure/CMakeLists.txt
src/data_structure/sarray/sarray.c
src/data_structure/sarray/sarray.h
src/data_structure/smap/CMakeLists.txt
src/data_structure/smap/smap.c
src/data_structure/smap/smap.h
src/protocol/data/resp/cmd_smap.h
src/protocol/data/resp/request.c
src/protocol/data/resp/request.h
src/rust-util/pelikan-sys/build.rs
src/rust-util/pelikan-sys/src/lib.rs
src/server/rds/CMakeLists.txt
src/server/rds/data/CMakeLists.txt
src/server/rds/data/cmd_smap.c
src/server/rds/data/cmd_smap.h
src/server/rds/data/process.c
src/server/rds/data/process.h
test/data_structure/CMakeLists.txt
test/data_structure/sarray/check_sarray.c
test/data_structure/smap/CMakeLists.txt
test/data_structure/smap/check_smap.c
test/integration/base.py
test/integration/client.py
test/integration/loader.py
test/integration/server.py
test/integration/test_twemcache.py

Generalizing sorted array a bit to allow fixed size values associated with (numeric) keys. Other than changing the signature of three APIs, and small changes to internal implementations, it looks and works very similar to sorted array.
Once this is merged I'm gonna start adding higher level APIs for SortedMap. Since we can use zero value size as a special case to get sorted array behavior with sorted map, I will probably port the sorted array APIs to use sorted map, and drop the sorted array data structure entirely.

Sorted map

---

Cargo.lock
src/storage/cdb/cdb_rs/Cargo.toml
src/storage/cdb/cdb_rs/build.rs
src/storage/cdb/cdb_rs/src/cdb/backend.rs
src/storage/cdb/cdb_rs/src/cdb/errors.rs
src/storage/cdb/cdb_rs/src/cdb/ffi/gen.rs
src/storage/cdb/cdb_rs/src/cdb/ffi/mod.rs
src/storage/cdb/cdb_rs/src/cdb/input.rs
src/storage/cdb/cdb_rs/src/cdb/mod.rs
src/storage/cdb/cdb_rs/src/cdb/storage.rs
src/storage/cdb/cdb_rs/src/lib.rs
src/storage/cdb/cdbgen/Cargo.toml
src/storage/cdb/cdbgen/src/gen/mod.rs
src/storage/cdb/cdbgen/src/lib.rs
src/storage/cdb/cdbgen/src/main.rs

Changes cdb crates to use Rust 2018 edition syntax.
Changes to use explicit versions in cargo manifest for
dependencies. Updates some dependencies to newer versions.
Added license headers.

update cdb to Rust 2018 edition

---

src/server/pingserver/admin/process.c
src/server/pingserver/admin/process.h
src/server/pingserver/main.c
src/server/pingserver/setting.c
src/server/pingserver/setting.h
src/server/rds/main.c
src/server/rds/setting.c
src/server/rds/setting.h
src/server/slimcache/admin/process.c
src/server/slimcache/admin/process.h
src/server/slimcache/main.c
src/server/slimcache/setting.c
src/server/slimcache/setting.h
src/server/twemcache/main.c
src/server/twemcache/setting.c
src/server/twemcache/setting.h

enabling dumping stats to a configurable file at configurable interval for all C binaries.

add stats_log to all C binaries

---

CMakeLists.txt
src/core/data/server.c
src/core/data/shared.h
src/core/data/worker.c

**event_fd** is much faster and easier to use to cross thread/process [notification](https://man7.org/linux/man-pages/man2/eventfd.2.html).
**event_fd** is a basically an atomic uint64 counter, that acts like _pollable_ file descriptor and was designed specifically for notification purposes.

use eventfd for notifications b/w server and worker

---

.github/workflows/ci.yml

Adds a first-pass port of the travisci config to GitHub Workflows.

add github workflow for ci

---

Cargo.lock
Cargo.toml
config/pingserver-tls.toml
src/client/pingclient-rs/Cargo.toml
src/client/pingclient-rs/src/main.rs
src/rust/buffer/Cargo.toml
src/rust/buffer/src/lib.rs
src/rust/config/src/lib.rs
src/rust/config/src/pingserver.rs
src/rust/config/src/tls.rs
src/server/pingserver-rs/Cargo.toml
src/server/pingserver-rs/src/event_loop.rs
src/server/pingserver-rs/src/logger.rs
src/server/pingserver-rs/src/main.rs
src/server/pingserver-rs/src/server.rs
src/server/pingserver-rs/src/session.rs
src/server/pingserver-rs/src/worker.rs
test/server/pingserver-rs/src/lib.rs

Adds TLS support to the rust pingserver using rustls. This allows
us to support TLS 1.3 and 1.2. TLS handshake occurs on the server
thread, so new connections will not interfere with request
processing on the worker thread.
Adds a simple pingclient with TLS support so we can get basic perf
numbers to compare with and without TLS.
Fixes an issue where the rust pingserver may fail to accept new
connections.

add TLS support to rust pingserver

---

test/server/pingserver-rs/src/lib.rs

Re-enables tests that don't hang. The "large ping" test still hangs
with the current implementation, so it is left disabled.
Adds a test that sends an invalid command and expects a hangup.

pingserver integration test cleanup

---

Cargo.lock
src/rust/config/src/admin.rs
src/server/pingserver-rs/Cargo.toml
src/server/pingserver-rs/src/admin.rs
src/server/pingserver-rs/src/common.rs
src/server/pingserver-rs/src/event_loop.rs
src/server/pingserver-rs/src/main.rs
src/server/pingserver-rs/src/metrics.rs
src/server/pingserver-rs/src/session.rs
src/server/pingserver-rs/src/worker.rs
test/server/pingserver-rs/src/lib.rs

Adds metrics using rustcommon-metrics library. Includes adding an
admin server port and thread to service stats requests. Instruments
applicable sections of the code to provide near-parity with the C
implementation of the pingserver.

add metrics to rust pingserver

---

Cargo.lock
src/server/pingserver-rs/Cargo.toml
src/server/pingserver-rs/src/metrics.rs

By using strum derive macros, we are able to simplify the metrics
definitions. As our metric names are well-formed enum variants, we
can simply convert the variant name to snake case and make use of
the enum variant iterator to handle registration.

pingserver-rs: use strum to derive metric names and enum iterator

---

Cargo.lock
src/server/pingserver-rs/Cargo.toml
src/server/pingserver-rs/src/admin.rs
src/server/pingserver-rs/src/common.rs
src/server/pingserver-rs/src/event_loop.rs
src/server/pingserver-rs/src/metrics.rs
src/server/pingserver-rs/src/server.rs
src/server/pingserver-rs/src/session.rs
src/server/pingserver-rs/src/worker.rs
src/server/pingserver-rs/tests/integration.rs

Replaces rustls with boringssl. This will be a better dependency
for long-term at the cost of an initial performance regression.

pingserver-rs: replace rustls with boringssl

---

ci/cargo.sh
src/server/pingserver-rs/src/admin.rs
src/server/pingserver-rs/tests/integration.rs

Fixes a bug in the stats output corresponding to issue #317 by
adding the terminating "END\r\n" to the admin response.
Fixes #317

pingserver-rs: bugfix for stats output

---

Cargo.lock
src/server/pingserver-rs/Cargo.toml
src/server/pingserver-rs/src/admin.rs
src/server/pingserver-rs/src/common.rs
src/server/pingserver-rs/src/event_loop.rs
src/server/pingserver-rs/src/lib.rs
src/server/pingserver-rs/src/metrics.rs
src/server/pingserver-rs/src/server.rs
src/server/pingserver-rs/src/session.rs
src/server/pingserver-rs/src/worker.rs
src/server/pingserver-rs/tests/integration.rs

Adds rusage metrics to pingserver to address #314
Replaces the current metrics library with one being developed for
twemcache-rs. It removes overhead of a hash lookup for each metric
increment by using a fixed indexing from the metric enum into a
vec of channels.
On a test host this is giving ~4-5% gain in peak throughput.

pingserver-rs: add rusage metrics

---

scripts/capacity/calculator.py
src/data_structure/sarray/sarray.c
src/protocol/data/memcache/response.c
src/protocol/data/memcache/response.h
src/server/twemcache/main.c
src/storage/slab/item.c
src/storage/slab/slab.c
src/time/time.h

1. add a new field in memcache response that Segcache will use to decrease ref count after serving; 
2. change the timer in pelikan_twemcache so that the default timer is memcached_time; 
3. fix a bug in pelikan_twemcache where flush_at is not reset during tear and setup. 
4. add segcache in calculator

[pre-segcache] preparations for segcache 

---

Cargo.lock
ci/run.sh
deps/ccommon/.gitignore
deps/ccommon/CMakeLists.txt
deps/ccommon/include/hash/xxhash.h
deps/ccommon/src/cc_debug.c
test/server/CMakeLists.txt

Update with latest upstream of ccommon

Ccommon update

---

src/storage/seg/segmerge.c

Segcache currently doesn't properly decrement the item_curr_bytes
or item_curr gauges when items are removed during segment merge.
Adds decrement for both counters during merge phase.

segcache: fix incorrect item stats following merge

---

README.md

Adds the Rust servers, as well as some build/config information to
the top-level README.

docs: add Rust servers to top-level README

---

src/rust/server/segcache/tests/common.rs
src/rust/storage/seg/src/hashtable/mod.rs

The Rust implementation of seg storage appears to have a simple bug
which can result in an incorrect result for a CAS operation.
If the CAS value in the hashtable does not match the provided
value, the code immediately returns that the item exists which is
used to indicate a stale CAS value. However, it does not check if
the item is actually in the table or if this is just a collision.
Changes the code to scan through the items in the bucket even if
the CAS value does not match.

bugfix: seg storage CAS may give incorrect result

---

ci/cargo.sh
src/rust/storage/seg/src/tests.rs

CI failed to catch a failure in PR #339 related to a struct size test that was not updated with the corresponding change to the struct.
This change causes the CI job to properly fail and then fixes the test so that CI passes.

ci: fix uncaught failure in #339

---

.github/workflows/cargo.yml

The cargo audit failures have been addressed and we should
re-enable this check in CI.

enable cargo audit in CI

---

src/rust/core/server/src/threads/admin.rs
src/rust/session/src/lib.rs
src/rust/session/src/stream.rs
src/rust/storage/seg/src/seg.rs
src/rust/storage/seg/src/segments/segment.rs
src/rust/storage/seg/src/segments/segments.rs

Adds gauge for current open connections: `tcp_conn_curr`
Changes RSS stats to export as bytes instead of kilobytes.
Fix live/dead item tracking, consolidate updates, add comments.

segcache_rs stats cleanup

---

Cargo.lock
src/rust/core/server/src/lib.rs
src/rust/core/server/src/threads/admin.rs
src/rust/core/server/src/threads/mod.rs
src/rust/server/pingserver/Cargo.toml
src/rust/server/pingserver/src/main.rs
src/rust/server/segcache/Cargo.toml
src/rust/server/segcache/src/main.rs

Adds basic implementation of the command line options requested in #361 
Adds help and usage information to segcache-rs and pingserver-rs. Also adds
options to display version and stats.
Note: stats descriptions and config information are not yet implemented and
will be added in a follow-up PR.

add command line options to rust servers

---

src/rust/protocol/fuzz/fuzz_targets/memcache.rs
src/rust/protocol/src/memcache/wire/mod.rs
src/rust/protocol/src/memcache/wire/request/command.rs
src/rust/protocol/src/memcache/wire/request/mod.rs
src/rust/protocol/src/memcache/wire/request/parse.rs
src/rust/protocol/src/memcache/wire/request/test.rs
src/rust/protocol/src/memcache/wire/response/mod.rs

The command `flush_all` is required for some internal tooling and
can be added to pelikan_segcache_rs as a no-op (similar to slimcache).
This causes the command to be handled like a noreply and leaves the
connection open.

segcache_rs: add no-op support for flush_all command

---

config/segcache.toml
src/rust/core/server/src/threads/admin.rs
src/rust/protocol/src/admin.rs

Adds a 'flush_all' command to the admin protocol with a no-op
handler. This will enable internal tooling to connect to the admin
port and issue a 'flush_all' and have the connection remain open.
For #365 we will implement the actual functionality for this
command.

segcache_rs: add 'flush_all' as no-op admin command

---

src/rust/core/server/src/poll/mod.rs
src/rust/core/server/src/threads/listener.rs
src/rust/core/server/src/threads/traits/event_loop.rs
src/rust/core/server/src/threads/worker/multi.rs
src/rust/core/server/src/threads/worker/single.rs
src/rust/session/src/lib.rs

Improve the trace logging throughout rust core to reference the session peer address and print garbage bytes for bad requests. These changes make it easier to understand the flow for sessions, particularly in multi-worker configuration where session ids are not unique across workers.

rust/core: improve trace logging

---

src/rust/core/server/src/poll/mod.rs
src/rust/core/server/src/threads/listener.rs

Currently the listener thread is responsible for calling accept on
the `TcpListener` and driving TLS negotiation. Under heavy connect
pressure, we observe timeouts which may be due to contention
between accepting new TCP connections and driving the TLS
handshakes.
To conserve work put into partially negotiated TLS sessions, we
change the behavior of calling accept on the `TcpListener` to be
called only once per loop. This allows us to prioritize handling
partially negotiated TLS sessions to avoid timeouts during the
handshake phase.

rust core: improve TLS negotiation behavior

---

src/rust/core/server/src/threads/worker/mod.rs
src/rust/core/server/src/threads/worker/storage.rs

Adds a new metric which tracks the distribution of the storage
queue depth at the start of each iteration.

rust/core: track depth of storage queue

---

src/rust/core/server/src/threads/traits/event_loop.rs
src/rust/protocol/src/memcache/wire/request/parse.rs
src/rust/protocol/src/memcache/wire/request/test.rs
src/rust/server/segcache/tests/common.rs

Bugfixes for memcache protocol handling.
Fix calculation of how many bytes to consume off the buffer.
Allow middle-whitespace in get request: eg `get  0\r\n` (note: two spaces)
Allow null bytes in key.
Adds some additional tests.
Fixes: #371

rust: memcache protocol fixes

---

Cargo.lock

Updates the rustcommon dependency which gets us sub-second
precision timestamps.

logger: update rustcommon to get sub-second timestamps

---

src/rust/core/server/src/process/builder.rs
src/rust/core/server/src/threads/admin.rs

During startup we use the logging framework to note any fatal
errors during initialization. However, the log might not be flushed
before program termination. This results in useful messages being
lost.
This change adds log flushing before termination so that we can get
useful messages about fatal errors during initialization.
Fixes #372

rust/core: flush log before exiting

---

src/rust/storage/seg/src/seg.rs
src/rust/storage/seg/src/segments/segments.rs

Bugfix for segment request stats not incrementing unless eviction
was required.
Successful segment acquisition now results in stats being updated.

segcache-rs: fix segment request stats

---

src/rust/storage/seg/src/segments/segments.rs

Adds an `evict_time` stat which tracks the time spent handling
segment eviction.

seg: track time spent in eviction

---

config/segcache.toml
src/rust/common/src/ssl.rs
src/rust/config/src/tls.rs

Fixes for TLS certificate chain loading when presented with both
a server cert and chain.

rust: fix tls certificate chain loading

---

src/rust/entrystore/src/lib.rs
src/rust/protocol/src/memcache/wire/mod.rs
src/rust/protocol/src/memcache/wire/request/mod.rs
src/rust/protocol/src/memcache/wire/request/parse.rs

Adds stats to track request cardinality for GET and GETS commands.
This allows us to get insight into batch size distribution over
time which can provide better insight into traffic patterns.

protocol/memcache: add request cardinality distribution stats

---

Cargo.lock
src/rust/common/Cargo.toml
src/rust/common/src/ssl.rs
src/rust/core/server/Cargo.toml
src/rust/core/server/src/threads/admin.rs
src/rust/core/server/src/threads/listener.rs
src/rust/session/Cargo.toml
src/rust/session/src/lib.rs
src/rust/session/src/stream.rs

Updates `boring` crate to 2.0.0 which uses the same version of
boringssl but has improvements in the rust wrapper.
Centralizes dependency in the common crate

rust: update boringssl

---

src/rust/entrystore/src/seg/memcache.rs
src/rust/entrystore/src/seg/mod.rs
src/rust/protocol/src/memcache/storage/mod.rs
src/rust/protocol/src/memcache/wire/mod.rs
src/rust/protocol/src/memcache/wire/response/mod.rs
src/rust/server/segcache/tests/common.rs
src/rust/storage/seg/src/error.rs
src/rust/storage/seg/src/hashtable/mod.rs
src/rust/storage/seg/src/item/mod.rs
src/rust/storage/seg/src/item/raw.rs
src/rust/storage/seg/src/seg.rs
src/rust/storage/seg/src/tests.rs
src/rust/storage/types/src/lib.rs

Adds support for incr/decr commands to segcache-rs.
In the storage library, we explicitly implement these commands
as wrapping_add() and saturating_sub(). This allows us to choose
the behaviors at higher-levels and potentially make additional
operations available in different protocols.
The implementation in segcache-rs aims to be memcached
compatible and returns "ERROR" when numeric operations are
attempted on non-numeric values.
Replaces #383 and #395

segcache-rs: add incr/decr support

---

Cargo.lock
src/rust/core/server/Cargo.toml
src/rust/queues/Cargo.toml
src/rust/session/Cargo.toml

Updates mio to 0.8.0. See changelog for details (https://github.com/tokio-rs/mio/blob/master/CHANGELOG.md). No performance change detected in testing with pingserver

rust: update mio to 0.8.0

---

src/rust/entrystore/src/noop/ping.rs
src/rust/protocol/admin/src/admin.rs
src/rust/protocol/common/src/lib.rs
src/rust/protocol/memcache/src/memcache/wire/request/command.rs
src/rust/protocol/ping/Cargo.toml
src/rust/protocol/ping/benches/ping.rs
src/rust/protocol/ping/fuzz/fuzz_targets/ping.rs
src/rust/protocol/ping/src/ping/mod.rs
src/rust/protocol/ping/src/ping/wire/mod.rs
src/rust/protocol/ping/src/ping/wire/request/compose.rs
src/rust/protocol/ping/src/ping/wire/request/keyword.rs
src/rust/protocol/ping/src/ping/wire/request/mod.rs
src/rust/protocol/ping/src/ping/wire/request/parse.rs
src/rust/protocol/ping/src/ping/wire/response/compose.rs
src/rust/protocol/ping/src/ping/wire/response/keyword.rs
src/rust/protocol/ping/src/ping/wire/response/mod.rs
src/rust/protocol/ping/src/ping/wire/response/parse.rs
src/rust/protocol/ping/src/ping/wire/response/test.rs
src/rust/server/pingserver/Cargo.toml
src/rust/server/pingserver/src/lib.rs

We need to implement request composition and response parsing so
that a proxy is able to be protocol aware. This also makes it
possible to use this protocol crate for a client.

protocol/ping: make request and response symmetric

---

Cargo.lock
src/rust/core/server/src/threads/listener.rs
src/rust/core/server/src/threads/workers/multi.rs
src/rust/core/server/src/threads/workers/single.rs
src/rust/core/server/src/threads/workers/storage.rs
src/rust/queues/Cargo.toml
src/rust/queues/src/lib.rs
src/rust/storage/seg/src/builder.rs
src/rust/storage/seg/src/eviction/mod.rs
src/rust/storage/seg/src/hashtable/hash_bucket.rs
src/rust/storage/seg/src/hashtable/mod.rs
src/rust/storage/seg/src/seg.rs
src/rust/storage/seg/src/segments/segments.rs
src/rust/storage/seg/src/ttl_buckets/ttl_bucket.rs

Some optimizations for segcache performance. On a test system this
gives somewhere around 2% more performance. Benefit may vary
depending on config and workload.
- Reduce calls to Instant::recent() to reduce atomics in hot path.
- Remove trace logging in hot path.
- Change ordering of fields to optimize hot path.
- Use crossbeam_queue instead of crossbeam_channel to remove
unnecessary channel level wake.

segcache optimizations

---

Cargo.lock
config/segcache.toml
src/rust/config/src/admin.rs
src/rust/core/server/Cargo.toml
src/rust/core/server/src/threads/admin.rs

Adds a http admin port to the rust servers to expose statistics in
human, json, and prometheus formats.

add http admin port to rust servers

---

src/rust/core/server/src/process/mod.rs
src/rust/core/server/src/threads/admin.rs
src/rust/server/pingserver/src/lib.rs
src/rust/server/pingserver/tests/integration.rs
src/rust/server/segcache/src/lib.rs
src/rust/server/segcache/tests/common.rs
src/rust/server/segcache/tests/integration.rs
src/rust/server/segcache/tests/integration_multi.rs

For the rust servers, the version number reported on the admin port
reflects that of the 'core/server' crate instead of the actual
version number for the binary.
Changes the process and admin builders to allow setting a version
number. Updates the pingserver and segcache binary crates to set
the version number based on their cargo metadata.

fix reported version numbers

---

src/rust/storage/seg/src/hashtable/mod.rs
src/rust/storage/seg/src/item/header.rs
src/rust/storage/seg/src/item/raw.rs
src/rust/storage/seg/src/seg.rs
src/rust/storage/seg/src/segments/segment.rs
src/rust/storage/seg/src/segments/segments.rs

Makes the item header immutable in the Rust implementation of
Segcache by removing use of the `deleted` bit in the item header.
Since the Rust implementation of segment storage is not concurrent,
there is no need for the `deleted` bit in the item header. Instead,
we can check the hashtable to confirm if the item is located within
a given segment at a specified offset. By removing the use of the
`deleted` bit, we make the item header immutable. This is
beneficial in that it removes the need to perform random updates
within the segments.

segcache: make item header immutable

---

src/rust/config/src/segcache.rs
src/rust/server/segcache/src/main.rs

debatably fixes #331
I could see this needing to be a bit more self-describing in the future, but this will at least make it easy for the enduser to see the precise configuration in use.
I tried doing this with as minimal investment as possible, hence using Serde/TOML, which seems sensible enough given that that's seemingly the configuration language of choice in the Rust part of Pelikan.
Screenshots:

feat: #331 Prints the configuration in use for the server and then exits

---

src/rust/common/src/bytes.rs
src/rust/common/src/lib.rs
src/rust/protocol/admin/src/admin.rs

fixes #368 by trimming the command of leading/trailing whitespace before matching
I'm assuming this is what is intended based on reading the C code, but I might be wrong

feat: #368 make admin protocol parsing tolerant of leading/trailing whitespace

---

src/rust/storage/seg/src/hashtable/mod.rs
src/rust/storage/seg/src/rand.rs
src/rust/storage/seg/src/seg.rs
src/rust/storage/seg/src/segments/segment.rs
src/rust/storage/seg/src/segments/segments.rs

As noted in #414, we can use iterators to reduce code duplication
within the hashtable module.
This change adds two iterator types to the hashtable, allowing us
to iterate through item info entries for a given hash.

refactor: use iterators in seg hashtable

---

src/core/context.h
src/core/core.c

Minor header changes to get the core module to compile/link correctly with gcc 11.

Squelch devtoolset-11 compile errors

---

src/rust/storage/seg/src/hashtable/mod.rs
src/rust/storage/seg/src/segments/segment.rs

The logic during removing an item is incorrect. This change fixes
and simplifies the logic when making changes to the item info
entries. Since this implementation is not concurrent, we can
guarantee that the only time we may have a stale item is during an
insert. As the insert logic cleans up the stale item, all other
functions can trust that the first match is the current item.

fix: incorrect logic when removing and replacing items

---

src/rust/core/proxy/src/backend.rs
src/rust/core/proxy/src/frontend.rs

Add counter for tracking epoll returns max events in proxy frontend and backend

Add metric for tracking epoll max events in proxy

---

src/core/server/src/threads/workers/mod.rs
src/core/server/src/threads/workers/multi.rs
src/core/server/src/threads/workers/single.rs
src/core/server/src/threads/workers/storage.rs

Previously, we used `Instant::recent()` to get a cached view of the
monotonic clock and used that to set the timestamp for the
sessions. This could result in incorrect latency reporting if the
cached value is sufficiently stale or if another thread refreshes
the cached value while a thread is processing many events.
This change corrects how the latency is being measured by using
`Instant::now()` when poll returns as the timestamp for all events
being processed in that loop iteration.

core/server: fix how latencies are calculated

---

Cargo.lock
src/protocol/memcache/Cargo.toml
src/protocol/memcache/src/lib.rs
src/protocol/memcache/src/response/client_error.rs
src/protocol/memcache/src/response/deleted.rs
src/protocol/memcache/src/response/error.rs
src/protocol/memcache/src/response/exists.rs
src/protocol/memcache/src/response/not_found.rs
src/protocol/memcache/src/response/not_stored.rs
src/protocol/memcache/src/response/numeric.rs
src/protocol/memcache/src/response/server_error.rs
src/protocol/memcache/src/response/stored.rs
src/protocol/memcache/src/response/values.rs
src/protocol/memcache/src/result/mod.rs

The memcache command log (klog) was missing following the protocol
refactor in #430.
This change adds the command log back for the memcache protocol.

fix: memcache command log

---

src/entrystore/src/seg/memcache.rs
src/protocol/memcache/src/lib.rs
src/protocol/memcache/src/request/add.rs
src/protocol/memcache/src/request/append.rs
src/protocol/memcache/src/request/cas.rs
src/protocol/memcache/src/request/mod.rs
src/protocol/memcache/src/request/prepend.rs
src/protocol/memcache/src/request/replace.rs
src/protocol/memcache/src/request/set.rs
src/protocol/memcache/src/util.rs
src/proxy/momento/src/klog.rs
src/proxy/momento/src/protocol/memcache/set.rs
src/proxy/momento/src/protocol/resp/set.rs

Adds a new type `Ttl` to be used throughout the memcache protocol crate. This allows us to define and document the conversion between external and internal representations of the TTL.
Fixes #456

consolidate TTL conversion logic

---

.github/workflows/cargo.yml
Cargo.lock
config/pingserver.toml
src/core/admin/Cargo.toml
src/core/admin/src/lib.rs

The http port for the admin thread is missing after #453. This change reintroduces this functionality using previous code and adds a CI test which validates the stats endpoint.

fix: http admin missing after #453

---

Cargo.lock
Cargo.toml
src/storage/bloom/Cargo.toml
src/storage/bloom/benches/bloom.rs
src/storage/bloom/src/lib.rs

This PR introduces a bloom filter storage module. At the moment it only contains the bloom filter data structure, docs, benchmarks, and tests. In future PRs I will add a protocol that makes use of the bloom filter.
I don't think I could get this to be appreciably faster if I tried. I have added some criterion benchmarks under `src/storage/bloom/benches`. Here are the results:
```
unit                    time:   [116.81 ns 118.67 ns 120.47 ns]
u64                     time:   [130.20 ns 131.42 ns 132.77 ns]
small_slice             time:   [251.02 ns 252.92 ns 254.75 ns]
large_slice             time:   [21.259 µs 21.306 µs 21.352 µs]
```

Add a bloom filter storage module

---

src/server/segcache/tests/common.rs
src/storage/bloom/src/lib.rs

For some reason, the segcache integration tests can be flakey in the CI environment.
In order to get CI tests to be trustworthy, we need to make sure any flakey tests are fixed or removed so that we can rely on the status of the tests.

ci: fix flakey tests

---

Dockerfile
README.md

Docker build was failing with following error.
```console
=> [cargo-build 5/8] RUN apt-get install -y clang                                                                                                                                                                                                      17.5s
=> ERROR [cargo-build 6/8] RUN mkdir .cargo                                                                                                                                                                                                             0.3s
------
> [cargo-build 6/8] RUN mkdir .cargo:
#14 0.251 mkdir: cannot create directory '.cargo': File exists
------
executor failed running [/bin/sh -c mkdir .cargo]: exit code: 1 …
```

Momento proxy fixes

---

.github/workflows/cargo.yml
.github/workflows/fuzz.yml

We're using a deprecated version of ubuntu for GH CI. Changes the workflow configs to use `ubuntu-latest`.
Also trying bumping the macos version to 12, in the hopes that it is less likely to be flakey.

ci: update runner os versions

---

src/server/pingserver/src/main.rs
src/server/segcache/src/main.rs

This was noticed in the review of #468. We should really be writing error messages to stderr. This PR switches segcache and pingserver over to using eprintln.

Make error messages in segcache and pingserver use stderr

---

src/config/src/segcache.rs
src/net/src/tls_tcp.rs
src/server/pingserver/src/main.rs
src/server/segcache/src/main.rs

The panic hook should really print to stderr directly instead of using
a log macro, as we cannot guarantee the logger flushes before the
program terminates. 
Also improves some of the error messages for loading TOML configs
and TLS key materials to print the filename as well as the error
message.

fix: improve error messages
