src/protocol/data/ping/compose.c, src/protocol/data/ping/parse.c, src/protocol/data/ping/request.h, src/server/pingserver/data/process.c, src/server/pingserver/data/process.h, src/server/pingserver/main.c
- Added error handler
- Allow 'ping' (lower case)
error handling and 'ping' individually tested (not included in the PR)
=> Fix pingserver

LICENSE, src/data_structure/CMakeLists.txt, src/data_structure/shared.h, src/data_structure/ziplist/CMakeLists.txt, src/data_structure/ziplist/README.md, src/data_structure/ziplist/ziplist.c, src/data_structure/ziplist/ziplist.h, test/data_structure/CMakeLists.txt, test/data_structure/bitmap/check_bitmap.c, test/data_structure/ziplist/CMakeLists.txt, test/data_structure/ziplist/check_ziplist.c
Ziplist and unit tests added. Note this is significantly different from the Redis version, though proper references are provided. Please see comment in source for details.
As a result of the difference, the code here is significantly shorter, less than half of the LOC compared to Redis' ziplist.
=> Adding ziplist

CMakeLists.txt, ci/run.sh, src/storage/CMakeLists.txt
only look for rust if we need it
=> Unbreak the build

src/server/cdb/data/process.c
make sure we actually release memory after the req/res cycle
=> bad fork of twemcache, fix memory leak

test/CMakeLists.txt, test/integration/CMakeLists.txt
make test successfully triggers integration test:
```
...
Start 23: integration
23/23 Test #23: integration ......................   Passed    0.15 sec
```
=> create a CMake target for integration test

src/protocol/data/memcache/response.h, src/server/cdb/main.c, src/storage/cdb/cdb.h, src/storage/cdb/cdb_ffi/src/ccommon/bstring.rs, src/storage/cdb/cdb_ffi/src/lib.rs, src/storage/cdb/cdb_rs/src/cdb/mod.rs, src/storage/cdb/cdb_rs/src/lib.rs
User now has the choice of running the CDB from heap or from an
mmapped file.
=> CDB: add mmap backend

src/protocol/data/memcache/response.h, src/server/cdb/main.c, src/storage/cdb/cdb.h, src/storage/cdb/cdb_ffi/src/ccommon/bstring.rs, src/storage/cdb/cdb_ffi/src/lib.rs, src/storage/cdb/cdb_rs/src/cdb/mod.rs, src/storage/cdb/cdb_rs/src/lib.rs
Reverts twitter/pelikan#183
Don't want to merge this quite yet, I'm working on integrating the most recent ccommon changes first, this may be easier to do manually, as it conflicts pretty badly with my branch
=> Revert "CDB: add mmap backend"

src/core/admin/admin.c, src/protocol/admin/compose.c, src/protocol/admin/compose.h, src/protocol/admin/parse.c, src/protocol/admin/parse.h, src/protocol/data/memcache/compose.c, src/protocol/data/memcache/compose.h, src/protocol/data/memcache/parse.c, src/protocol/data/memcache/parse.h, src/protocol/data/ping/compose.c, src/protocol/data/ping/compose.h, src/protocol/data/ping/parse.c, src/protocol/data/ping/parse.h, src/protocol/data/redis/parse.c, src/protocol/data/redis/parse.h, src/protocol/data/redis/token.c, src/protocol/data/redis/token.h, src/server/cdb/data/process.c, src/server/pingserver/data/process.c, src/server/redis/data/process.c, src/server/slimcache/data/process.c, src/server/slimredis/data/process.c, src/server/twemcache/data/process.c
=> follow style guide for compose/parse rstatus enum

ci/before-install.sh, ci/install-check.sh, deps/ccommon/ci/before-install.sh, deps/ccommon/ci/install-check.sh
this shows the age of my shell script snippets :)
Tested this with both python `2.7.14` and `3.6.3`.
=> fix python2-ism

src/client/network/cli_network.h, src/client/resp_cli/main.c, src/core/data/server.c, src/core/data/worker.c, src/data_structure/ziplist/ziplist.h, src/hotkey/hotkey.c, src/rust-util/pelikan/src/core/mod.rs, src/server/cdb/data/process.c, src/server/rds/data/cmd_sarray.c
Fixes some spelling errors in comments and log messages
=> fixes spelling errors

src/server/segcache/data/process.c, src/storage/seg/constant.h, src/storage/seg/hashtable.c, src/storage/seg/hashtable.h, src/storage/seg/item.c, src/storage/seg/item.h, src/storage/seg/seg.c, src/storage/seg/seg.h, src/storage/seg/segevict.c, src/storage/seg/segmerge.c, src/storage/seg/ttlbucket.c, test/storage/seg/check_seg.c
The current code should have no (at least no under my stress test) bug now.
=> [Segcache] clean up and bug fix 

src/rust/config/src/seg.rs, src/rust/entrystore/src/seg/mod.rs
There's a few changes in ccommon that we'd like to include within pelikan. This change brings ccommon up to the latest version.
=> Update ccommon to latest revision

Cargo.lock, src/rust/logger/Cargo.toml, src/rust/logger/src/lib.rs, src/rust/logger/src/outputs.rs, src/rust/logger/src/single.rs
Adds metrics to the rust logging crate.
=> add metrics for rust logger

src/rust/session/src/lib.rs
Add a stat which tracks the depth of the request pipeline per
session. This is achieved by tracking the number of responses
between resets of the session timestamp. This corresponds to the
number of complete requests in the session buffer for a single
read.
=> rust/session: track pipeline depth distribution

src/rust/storage/seg/src/seg.rs, src/rust/storage/seg/src/segments/segments.rs, src/rust/storage/seg/src/tests.rs, src/rust/storage/seg/src/ttl_buckets/mod.rs, src/rust/storage/seg/src/ttl_buckets/ttl_bucket.rs, src/rust/storage/seg/src/ttl_buckets/ttl_buckets.rs
Adds a function to clear the stored data.
=> storage/seg: add clear function

.github/workflows/cargo.yml, .github/workflows/cmake.yml, .github/workflows/fuzz.yml, README.md
Adding some more information at the top of the readme, including
more badges.
Gives Github workflows actual names so we can use them with
shields.io badges for better visual consistency.
=> docs: readme improvements

src/rust/common/src/signal.rs, src/rust/core/server/src/lib.rs, src/rust/core/server/src/threads/admin.rs, src/rust/core/server/src/threads/listener.rs, src/rust/core/server/src/threads/worker/multi.rs, src/rust/core/server/src/threads/worker/single.rs, src/rust/core/server/src/threads/worker/storage.rs, src/rust/entrystore/src/lib.rs, src/rust/entrystore/src/noop/mod.rs, src/rust/entrystore/src/seg/mod.rs
Adds support to flush the cache content by issuing the 'flush_all'
command via the admin port.
=> segcache-rs: add flush_all support

.github/actions/ca/action.yml, .github/actions/pingproxy/action.yml, .github/actions/pingserver/action.yml, .github/actions/rpc-perf/action.yml, .github/workflows/cargo.yml, src/rust/core/proxy/src/admin.rs, src/rust/core/proxy/src/listener.rs, src/rust/core/proxy/src/poll.rs, src/rust/core/proxy/src/process.rs
Partially fixes #420 by adding support to the proxy to perform TLS termination.
=> feat: add tls termination support to proxy

src/rust/common/src/metrics.rs, src/rust/config/src/momento_proxy.rs, src/rust/config/src/proxy.rs, src/rust/proxy/momento/src/commands/get.rs, src/rust/proxy/momento/src/commands/set.rs, src/rust/server/pingserver/src/main.rs
Addresses some clippy lint warnings by making minor changes to the
code.
=> fix: fixes some clippy lint warnings

src/rust/core/proxy/src/backend.rs, src/rust/core/proxy/src/frontend.rs, src/rust/core/server/src/threads/workers/mod.rs, src/rust/core/server/src/threads/workers/multi.rs, src/rust/core/server/src/threads/workers/single.rs
Add a heatmap for tracking the the number of events returned by epoll
=> Add heatmap for epoll events

src/storage/bloom/benches/bloom.rs, src/storage/bloom/src/lib.rs
=> Add license headers to all source files under `src/storage/bloom`

src/server/segcache/tests/common.rs
Reworks the integration test for segcache so that multi-step test cases run over the same connection to ensure proper sequencing.
=> ci: rework integration tests for segcache

src/common/src/expiry.rs, src/protocol/resp/src/message/array.rs, src/protocol/resp/src/message/bulk_string.rs, src/protocol/resp/src/message/error.rs, src/protocol/resp/src/message/integer.rs, src/protocol/resp/src/message/simple_string.rs, src/protocol/resp/src/request/mod.rs, src/protocol/resp/src/util.rs
removed some assignments to _
switchted from loop with an if break to a while 
added Eq to TimeType in the expiry.rs common code section
all tests from the root of pelikan pass
=> fix clippy warnings for github/pelikan/src/protocol/resp lib

src/proxy/momento/README.md
* fix broken links
* format docker commands to make it easier to read
=> chore: add Redis example to momento-proxy docs
